# Generated by Django 6.0.1 on 2026-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('close_at', models.DateTimeField()),
                ('open_at', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-close_at', '-open_at'),
            },
        ),
        migrations.AddField(
            model_name='systemstate',
            name='scheduled_pause_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('competitor', 'Competitor'), ('viewer', 'Viewer')], default='competitor', max_length=20),
        ),
    ]
